name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    env:
          DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
          
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
    - name: BlackDuck Scan
      uses: blackducksoftware/github-action@v2
      with:
          detect-version: 7.13.2
          scan-mode: RAPID
          #detect.tools.excluded: DETECTOR
          #blackduck.trust.cert: TRUE
          #detect.risk.report.pdf: TRUE
          github-token: ${{ secrets.GITHUB_TOKEN }}
          blackduck-url: https://testing.blackduck.synopsys.com/
          blackduckapitoken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          detect.project.name: mvnwebapp1
          detect.project.version.name: 1
          #args: --detect.project.name=$PROJECT --detect.excluded.detector.types=GRADLE
          
          
